### ISSUE TITLE
Session Handling broken?

### ISSUE THREAD

**Issue by jdriselvato** [mmattozzi/cocoa-rest-client#104]
I've used the client in the past with login before accessing other services and everything worked. With this latest update the sessions seem to be broken. After I log in and then run another api call, the session returns UNAUTHORIZED.

**Comment by mmattozzi** [comment]
In the latest release, I added an option in the Options menu to Disable Automatic Cookies. This is probably enabled and you should disable it. After that, I believe your sessions should work again. Sorry for the confusion-- it seems like most people _didn't_ want this implicit cookie handling because they wanted to explicitly test their APIs rather than rely on a hidden process to keep track of cookies.

**Comment by jdriselvato** [comment]
Perfect! I didn't noticed that was an option and I understand the want for that. This is now resolved!
