### ISSUE TITLE
JSON pretty print converts ints to strings

### ISSUE THREAD

**Issue by malhal** [mmattozzi/cocoa-rest-client#117]
Noticed this in Version 1.3.14 (19)

Doing request in Safari the ints are fine:
`{"id":3,"created_at":"2016-09-22 00:43:49","updated_at":"2016-09-22 00:43:49","password":"123456","venue_id":5,"created_by_id":1,"updated_by_id":1,"bssid":null,"latitude":null,"longitude":null,"ssid":null}`

In the client the ints are converted to strings:

<img width="1056" alt="screen shot 2016-09-22 at 01 50 02" src="https://cloud.githubusercontent.com/assets/916912/18733900/e9fa704a-8066-11e6-8dec-4ef3a2fd39fe.png">

**Comment by mmattozzi** [comment]
Thanks... I totally missed this. I was battling a loss of precision with the json parsing library I was using so I modified it to store the original text string rather than parsing the string into a number and then writing that number back out. However, it looks like the writer puts the string in quotes as if it was, well, a string. I'll see if I can fix this.

**Comment by mmattozzi** [comment]
I've fixed this in master by updating my fork of json-framework ... https://github.com/mmattozzi/json-framework/commit/aac08fda0d9355b4cfeeb7cd2ac15faaf88e85ad

**Comment by malhal** [comment]
Sorry at first glance it doesn't look like you have that as a submodule in this repo, please let me know how to test the fix. Thanks!

**Comment by mmattozzi** [comment]
Yeah, just run `pod install` to pull in the updates.
