### ISSUE TITLE
Very large response does not show at all

### ISSUE THREAD

**Issue by steveswinsburg** [mmattozzi/cocoa-rest-client#126]
I have a request that returns a very large response. Approximately 294Kb. The response window does not seem to show anything at all.

**Comment by mmattozzi** [comment]
Try deselecting `Syntax Highlighting` from the `View` menu.

**Comment by steveswinsburg** [comment]
Ok that worked but OMG my eyes!

**Comment by mmattozzi** [comment]
Yeah... I think this is a reality you'll have to live with. CocoaRestClient uses the very popular [AceView](https://ace.c9.io/) inside of a webkit view for syntax highlighting. If you're dealing with JSON or XML, you should still get black and white pretty printing when syntax highlighting is turned off -- but maybe you're not seeing that either because of the other issue you reported.
