### ISSUE TITLE
Response Body Text cut-off

### ISSUE THREAD

**Issue by brandtdaniels** [mmattozzi/cocoa-rest-client#40]
![screen shot 2014-05-07 at 1 46 55 pm](https://cloud.githubusercontent.com/assets/1013676/2908541/e1444fce-d628-11e3-8190-0ea40f9c015f.png)

**Comment by mikebowen** [comment]
I'm experiencing this behavior still, was this bug ever looked at?

Thx, Mike

**Comment by mmattozzi** [comment]
I believe this is fixed in master (unreleased). You can build it yourself and give it a try or email me directly and I'll give you a link... I would appreciate some external testing of the newest release before I push it out to everybody; lots of internal changes and also a new syntax highlighting library.

**Comment by mmattozzi** [comment]
I think this is fixed with the new layout and syntax highlighting library.
