### ISSUE TITLE
Pretty URL parameters table

### ISSUE THREAD

**Issue by pilot34** [mmattozzi/cocoa-rest-client#56]
If you set Content-Type: application/json ![](http://monosnap.com/image/FULoGds7HDQ3RjlJMlW7Wkc3k7FuI1.png)
and add POST params ![](http://monosnap.com/image/jORTaFRkQbpVDJIU0EX66UdW9H4Icj.png)

When you submit request, POST params are ignored and empty data will be sent.

I think you shouldn't ignore POST params in this case.

**Comment by mmattozzi** [comment]
Not sure that I agree with you here. POST params only make sense when the Content-Type is set to _application/x-www-form-urlencoded_. Providing a Content-Type of _application/json_ implies that the content of the request will be in JSON. Perhaps I should disallow any other content types besides form urlencoded when POST params are being entered rather than a raw body; but it doesn't make sense for the request to say it is sending JSON but actual try to send form encoded parameters. It also doesn't make sense for the app to try to format the POST parameters into a JSON body...

**Comment by pilot34** [comment]
Other workaround is add ability to user see what actual HTTPBody was sent to server. Plain text log for example. It will improve such confusions, when you don't understand what was sent.

**Comment by brmiller** [comment]
I disagree.  I work with [projects which use a combination of URL parameters and application/json POST bodies](http://openidm.forgerock.org/doc/bootstrap/integrators-guide/#adding-custom-endpoints-request "ForgeRock Custom Endpoint Action Request").  In this example, we use _action to tell our request processor that it is a specific type of request (an action) as opposed to a create, patch, or update via POST.  Perhaps restricting the POST params makes sense in the general/strict sense, but my guess is there are RESTful APIs that don't completely adhere to this.  Ours does. :)  Lifting this restriction would make CocoaRestClient usable by participants of all projects for which this is not the case.

**Comment by brmiller** [comment]
Duh.  Looks like I misread what was being discussed and also what I was trying to accomplish.  For the purposes of demonstrating REST APIs, I was looking to use this rest client to show the URL parameters (on a POST with Content-type: application/json) using the Request Body parameter table.  This did not work, and I somehow understood my issue to be this one.

On the consult of a trusted colleague, I see I have misunderstood completely -- the *Request Body* parameters are clearly when using *application/x-www-form-urlencoded* -- as *the POST body*, having nothing to do with URL parameters.  I momentarily lapsed that URL parameters and post body parameters are different and can coexist.  Fine.

What I *really* would like to see is a "pretty" URL parameter table (like the Request Body parameter form) to show url parameters (when I have lots) in a quicker, readable fashion.  This could be a nice feature.

Otherwise, I +1 the suggestion to alter the UI behavior in the case of non-application/x-www-form-urlencoded types!

**Comment by mikefinta** [comment]
> POST params only make sense when the Content-Type is set to application/x-www-form-urlencoded
>
> It also doesn't make sense for the app to try to format the POST parameters into a JSON body

Actually, that's exactly what you have to do in order to call a dot net .asmx service with json (strange but true); it only accepts a POST, with Content-Type=application/json and the parameters in the body

**Comment by mikefinta** [comment]
> POST params only make sense when the Content-Type is set to application/x-www-form-urlencoded
> 
> It also doesn't make sense for the app to try to format the POST parameters into a JSON body

Actually, that's exactly what you have to do in order to call a dot net .asmx service with json (strange but true); it only accepts a POST, with Content-Type=application/json and the parameters in the body

**Comment by mmattozzi** [comment]
URL Parameters table released in [Version 1.4.2](https://github.com/mmattozzi/cocoa-rest-client/releases/tag/1.4.2)
