### ISSUE TITLE
Long responses stay in a Loading state

### ISSUE THREAD

**Issue by Qonstrukt** [mmattozzi/cocoa-rest-client#60]
Unfortunately I don't have a public URL for you to test with right now, and I'm not sure at which lengths this starts occurring. But responses that could be JSON formatted in 1.3.7, no longer can in 1.3.8.
The output box just keeps showing "Loading <url>".

I'll see if I can clone the project later today and see what exception it's throwing.

**Comment by mmattozzi** [comment]
Let me know if you can pin down a certain file size where you start seeing problems. I moved off of the old syntax highlighting library because it didn't have support for ARC memory management and it was kind of ugly too. [ACEView](https://github.com/faceleg/ACEView) seemed to work well for all the tests I did, so I went with it, but I don't thin I tried anything larger than 1MB. 

Will the request work if you use the View menu to turn off syntax highlighting?

**Comment by Qonstrukt** [comment]
Ah, I was already looking for that option in the interface. With syntax highlighting turned off, everything works as expected.
It would be great if the default non syntax highlighted view would use a monospace font though. :smile:

**Comment by mmattozzi** [comment]
Monospaced font fixed in 1.3.9. I think syntax highlighting performance will depend on your computer, Webkit, and any optimizations made to the ACE editor... but I'd be interested to hear what people have experienced as the size file that causes things to lock up.
