### ISSUE TITLE
PUT body is not sent

### ISSUE THREAD

**Issue by AlexVonB** [mmattozzi/cocoa-rest-client#95]
Hi,

I'm using CocoaRestClient to test my API and am trying to make a PUT request. But the request body, no matter if entered as key/value pairs or raw data, is not sent to the server. The server works correctly, because a `curl` call like `curl -X PUT <URL> -d "action=add&cat=7" -H "Accept: application/json"` works just fine. Since there are no open issues regarding this I am a little suspicious whether or not I am making a dumb mistake...

Maybe wait for some +1s before looking into this.

Best, Alex

**Comment by mmattozzi** [comment]
I tried doing a PUT to http://httpbin.org/put and everything seemed to work OK. I think the issue here is that the `-d` option for curl also automatically changes the Content-Type of the request to `application/x-www-form-urlencoded` unless otherwise specified. CocoaRestClient does not automatically do that. So click the Headers tab and see what is there. You can pick from the `application/x-www-form-urlencoded` option from ContentType menu as a shortcut to manually entering the value. 

CocoaRestClient doesn't make the same automatic optimization like curl does because (according to the man page) curl is designed to emulate a web browser in this scenario. Whereas CRC is designed for more generic HTTP API testing.

**Comment by AlexVonB** [comment]
That worked perfectly, thank you!
